[package]
name = "datafusion-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "38.0.0"
tokio = { version = "1.36", features = ["macros", "rt", "sync", "rt-multi-thread"] }

